
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 19 20:04:51 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int IS_LTE = 31;
  public static final int MAP = 19;
  public static final int IS_GT = 28;
  public static final int L_BRACKET_SQUARED = 43;
  public static final int CHAR = 51;
  public static final int CONST = 6;
  public static final int R_BRACKET_CURLY = 46;
  public static final int HASH = 48;
  public static final int SEMI = 37;
  public static final int CONTINUE = 14;
  public static final int INTERFACE = 20;
  public static final int MINUS = 22;
  public static final int COLUMN = 38;
  public static final int R_BRACKET_CURVED = 42;
  public static final int BOOL = 52;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 35;
  public static final int IS_LT = 30;
  public static final int PLUS = 21;
  public static final int MULTIPLY = 23;
  public static final int L_BRACKET_CURLY = 45;
  public static final int IF = 7;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 34;
  public static final int LOGICAL_OR = 33;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PERCENT = 25;
  public static final int NUMBER = 49;
  public static final int IDENT = 50;
  public static final int L_BRACKET_CURVED = 41;
  public static final int BREAK = 3;
  public static final int IS_GTE = 29;
  public static final int VOID = 12;
  public static final int IS_E = 26;
  public static final int DUAL_INC = 47;
  public static final int UNION = 15;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int WHILE = 18;
  public static final int LOGICAL_AND = 32;
  public static final int R_BRACKET_SQUARED = 44;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int DEC = 36;
  public static final int INTERSECT = 16;
  public static final int IS_NE = 27;
  public static final int PRINT = 9;
  public static final int DO = 17;
}

